import 'dotenv/config'

export const env = {
  MONGDOB_URI: process.env.MONGDOB_URI,
  DATASEBASE_NAME: process.env.DATASEBASE_NAME,
  APP_HOST: process.env.APP_HOST,
  APP_PORT: process.env.APP_PORT,

  BUILD_MODE: process.env.BUILD_MODE,
  WEBSITE_URL_DEVELOPMENT: process.env.WEBSITE_URL_DEVELOPMENT,
  WEBSITE_URL_PRODUCTION: process.env.WEBSITE_URL_PRODUCTION,
  BREVO_API_KEY: process.env.BREVO_API_KEY,
  EMAIL_SENDER: process.env.EMAIL_SENDER,

  ACCESS_TOKEN_SECRET_SIGNATURE: process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
  ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_SECRET_SIGNATURE: process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
  REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE
}